Python wrapper bridge to c++ now talks ONLY to C++ and mrgingham
I.e. it doesn't talk to python anymore. Because on CentOS7.2 if I build a C++
thing that talks to numpy it barfs:

  g++ -Wall -Wextra -std=gnu99 -Wno-cast-function-type -I/usr/include/opencv -fvisibility=hidden -Wno-unused-function -Wno-missing-field-initializers -Wno-unused-parameter -Wno-strict-aliasing -Wno-int-to-pointer-cast -Wno-unused-variable -DOLD_OPENCV=1 -MMD -MP -g -fno-omit-frame-pointer -DVERSION='"1.1"' -pthread -fno-strict-aliasing -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -O3 -c -o/dev/null mrgingham_pywrap_cplusplus_bridge.cc  |& head -n 50
  cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /usr/include/numpy/ndarraytypes.h:7:0,
                   from /usr/include/numpy/ndarrayobject.h:17,
                   from /usr/include/numpy/arrayobject.h:15,
                   from mrgingham_pywrap_cplusplus_bridge.cc:5:
  /usr/include/numpy/npy_common.h:188:2: error: #error Must use Python with unicode enabled.
   #error Must use Python with unicode enabled.
    ^

So the C++ bridge doesn't touch Python, and does stuff with callbacks instead
Yuck. Callbacks will make stuff slower. With a newer distro, the python unicode
thing maybe isn't a problem. You can revert the commit on 2019/3/25 if you want
to try it again